
# 数据集配置
dataset:
  name: 'historical_doc'
  train_dir: './data/train'
  val_dir: './data/val'
  test_dir: './data/test'
  num_classes: 6
  image_size: [800, 800]

# 模型配置
model:
  backbone: 'resnet50'
  pretrained: true
  use_fpn: true
  embedding_dim: 1024
  transformer:
    hidden_dim: 768
    nhead: 8
    num_layers: 1
  rpn:
    anchor_sizes: [[32, 64, 128, 256, 512]]
    aspect_ratios: [[0.5, 1.0, 2.0]]
    fg_iou_thresh: 0.7
    bg_iou_thresh: 0.3
    batch_size_per_image: 256
    positive_fraction: 0.5

# 训练配置
train:
  batch_size: 8
  num_workers: 4
  lr: 0.0001
  weight_decay: 0.0001
  momentum: 0.9
  lr_step_size: 10
  lr_gamma: 0.1
  num_epochs: 50
  early_stopping: 10

# 评估配置
eval:
  batch_size: 4
  iou_threshold: 0.5

# 输出配置
output:
  save_dir: './output'
  log_dir: './logs'
  checkpoint_dir: './checkpoints'
  visualization_dir: './visualizations'